name: Flatpak Test
on:
  push:
    branches: [main]
  pull_request:      
  workflow_dispatch:
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-46
      options: --privileged
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: palette.flatpak
        manifest-path: org.xlights.xlights.yml
        cache-key: flatpak-builder-${{ github.sha }}
